apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certificates
  namespace: theidserver
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
   requests:
    storage: 10Mi