FROM aguacongas/aguacongastheidserver:unstable as base
COPY Aguacongas.TheIdServer.Private/appsettings.Docker.json .
COPY Aguacongas.TheIdServer.Private/wwwroot/appsettings.Docker.json ./wwwroot/appsettings.json
ENV ASPNETCORE_ENVIRONMENT=Docker
ENV ASPNETCORE_Kestrel__Certificates__Default__Path=/usr/local/share/ca-certificates/aspnetapp.crt
ENV ASPNETCORE_URLS="https://+:5443;http://+:5000"
ENV ASPNETCORE_HTTPS_PORT=5443
