using Geralt;
using System.ComponentModel.DataAnnotations;

namespace Aguacongas.TheIdServer.Identity.Argon2PasswordHasher;

/// <summary>
/// Argon2 password hasher options
/// </summary>
public class Argon2PasswordHasherOptions
{
    /// <summary>
    /// Number of iteration to use. 2 by default.
    /// </summary>
    public int Interations { get; set; } = 2;

    /// <summary>
    /// Memory to use. 67108864 by default.
    /// </summary>
    public int Memory { get; set; } = 67108864;

    /// <summary>
    /// Hash prefix to inform it was generated by this hasher. 0xA0 by default.
    /// </summary>
    public byte HashPrefix { get; set; } = 0xA2;
}
