namespace Aguacongas.TheIdServer.Identity.ScryptPasswordHasher;
public class ScryptPasswordHasherOptions
{
    public int IterationCount { get; set; } = 16384;

    public int BlockSize { get; set; } = 8;

    public int ThreadCount { get; set; } = 1;

    /// <summary>
    /// Hash prefix to inform it was generated by this hasher. 0xA0 by default.
    /// </summary>
    public byte HashPrefix { get; set; } = 0x0C;

}
