// Project: Aguafrommars/TheIdServer
// Copyright (c) 2023 @Olivier Lefebvre
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Aguacongas.TheIdServer.Oracle.Migrations
{
    public partial class UpdateClaimsKey : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey("PK_AspNetUserClaims", "AspNetUserClaims");
            migrationBuilder.DropColumn("Id", "AspNetUserClaims");
            migrationBuilder.AddColumn<string>("Id", "AspNetUserClaims", type: "STRING AS UUID GENERATED BY DEFAULT");
            migrationBuilder.AddPrimaryKey("PK_AspNetUserClaims", "AspNetUserClaims", "Id");

            migrationBuilder.DropPrimaryKey("PK_AspNetRoleClaims", "AspNetRoleClaims");
            migrationBuilder.DropColumn("Id", "AspNetRoleClaims");
            migrationBuilder.AddColumn<string>("Id", "AspNetRoleClaims", type: "STRING AS UUID GENERATED BY DEFAULT");
            migrationBuilder.AddPrimaryKey("PK_AspNetRoleClaims", "AspNetRoleClaims", "Id");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey("PK_AspNetUserClaims", "AspNetUserClaims");
            migrationBuilder.DropColumn("Id", "AspNetUserClaims");
            migrationBuilder.AddColumn<int>("Id", "AspNetUserClaims", type: "NUMBER GENERATED BY DEFAULT AS IDENTITY");
            migrationBuilder.AddPrimaryKey("PK_AspNetUserClaims", "AspNetUserClaims", "Id");

            migrationBuilder.DropPrimaryKey("PK_AspNetRoleClaims", "AspNetRoleClaims");
            migrationBuilder.DropColumn("Id", "AspNetRoleClaims");
            migrationBuilder.AddColumn<int>("Id", "AspNetRoleClaims", type: "NUMBER GENERATED BY DEFAULT AS IDENTITY");
            migrationBuilder.AddPrimaryKey("PK_AspNetRoleClaims", "AspNetRoleClaims", "Id");
        }
    }
}
