# This is a basic workflow to help you get started with Actions

name: Docker

# Controls when the workflow will run
on:
  push:
    branches:
    - main
    - release/*
    - preview/*
    
  pull_request:
    branches:
    - main
    - release/*
    - preview/*
  
  workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: aguacongas
          password: ${{ secrets.DOCKER_HUB_PAT }}
      -
        name: Build and push TheIdServer
        id: docker_build_theidserver
        uses: docker/build-push-action@v2
        with:
          push: true
          file: src/Aguacongas.TheIdServer/Dockerfile
          tags: aguacongas/theidserver:next
      -
        name: Build and push TheIdServerApp
        id: docker_build_theidserverapp
        uses: docker/build-push-action@v2
        with:
          push: true
          file: src/Aguacongas.TheIdServer.BlazorApp/Dockerfile
          tags: aguacongas/theidserverapp:next
          
