# This is a basic workflow to help you get started with Actions

name: Docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ master, preview/*, release/* ]
    tags: [ '*' ]
  pull_request: 
    branches: [ master, preview/*, release/* ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        uses: battila7/get-version-action@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: aguacongas
          password: ${{ secrets.DOCKER_HUB_PAT }}
      -
        name: Build and push TheIdServer Duende
        id: docker_build_theidserver_duende
        uses: docker/build-push-action@v2
        with:
          push: true
          file: src/Aguacongas.TheIdServer.Duende/Dockerfile
          tags: aguacongas/theidserver.duende:{{ steps.get_version.outputs.version }}
      -
        name: Build and push TheIdServer
        id: docker_build_theidserver
        uses: docker/build-push-action@v2
        with:
          push: true
          file: src/Aguacongas.TheIdServer.IS4/Dockerfile
          tags: aguacongas/theidserver:{{ steps.get_version.outputs.version }}
      -
        name: Build and push TheIdServerApp
        id: docker_build_theidserverapp
        uses: docker/build-push-action@v2
        with:
          push: true
          file: src/Aguacongas.TheIdServer.BlazorApp/Dockerfile
          tags: aguacongas/theidserverapp:{{ steps.get_version.outputs.version }}
          
