# This is a basic workflow to help you get started with Actions

name: Docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ master, preview/*, release/* ]
    tags: [ '*' ]
  pull_request: 
    branches: [ master, preview/*, release/* ]
  release:
   
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  duende:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: aguacongas
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build and push TheIdServer Duende
        id: docker_build_theidserver_duende
        uses: docker/build-push-action@v2
        env: 
          GITHIB_FEED_TOKEN: ${{ secrets.GITHIB_FEED_TOKEN }}
        with:
          push: true
          file: src/Aguacongas.TheIdServer.Duende/Dockerfile
          tags: aguacongas/theidserver.duende:${{ github.event.release.tag_name || 'next' }}
  is4:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: aguacongas
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build and push TheIdServer
        id: docker_build_theidserver
        uses: docker/build-push-action@v2
        env: 
          GITHIB_FEED_TOKEN: ${{ secrets.GITHIB_FEED_TOKEN }}
        with:
          push: true
          file: src/Aguacongas.TheIdServer.IS4/Dockerfile
          tags: aguacongas/theidserver:${{ github.event.release.tag_name || 'next' }}
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: aguacongas
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build and push TheIdServerApp
        id: docker_build_theidserverapp
        uses: docker/build-push-action@v2
        env: 
          GITHIB_FEED_TOKEN: ${{ secrets.GITHIB_FEED_TOKEN }}
        with:
          push: true
          file: src/Aguacongas.TheIdServer.BlazorApp/Dockerfile
          tags: aguacongas/theidserverapp:${{ github.event.release.tag_name || 'next' }}
