# Update all depencies each days if needed

name: Release 2.0 Dependencies

# Controls when the action will run.
on:
  # Triggers the workflow at 02:00 each days
  schedule:
    - cron: '0 2 * * *'
  # allow to launch the job manually
  workflow_dispatch:  

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the branch fix/dependencies with the PAT 
      - uses: actions/checkout@v2
        with:
          ref: maintain/1.0.0
          token: ${{ secrets.PAT }}
          fetch-depth: 0
      - name: Merge preview/1.0.0
        continue-on-error: true
        run: | 
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge origin/preview/2.0.0 --allow-unrelated-histories
      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.100' 
      # Run update depencies script
      - name: Update dependencies
        run: ./update-dependencies.ps1
        env:
          SRC_BRANCH: maintain/1.0.0
          DEST_BRANCH: preview/2.0.0
          GITHUB_TOKEN: ${{ secrets.PAT }}
